### ISSUE TITLE
Request for D&C DINO implementation

### ISSUE THREAD

**Issue by SoulOfWindTGN** [agwmon/MuDI#2]
Thank you for your great work on this project. I was wondering if it would be possible for you to provide an implementation of the Detect-and-Compare approach integrated with DINO. This would be immensely helpful for understanding the potential of these methods in combination and for benchmarking purposes.

Thank you very much for considering this request!

**Comment by agwmon** [comment]
Hi! Thanks for your interest on our work!

We plan to update our code to make it easier to use, 
and we’ll also add the D&C dino you mentioned.

**Comment by agwmon** [comment]
@SoulOfWindTGN 
Hi! Thanks for waiting!

We upload our Detect-and-Compare with DINOv2. Please check :blush:
