### ISSUE TITLE
Code for Flux

### ISSUE THREAD

**Issue by 1jsingh** [agwmon/MuDI#3]
Thanks for the amazing work!

I noticed that the paper also includes examples for flux with comparisons with dreambooth. Can you please point me to the training / inference code for flux for your approach?

**Comment by agwmon** [comment]
Hi! Thanks for your interest on our work!

We plan to update our code to make it easier to use, including FLUX code.
I'll share it as soon as it's ready!

**Comment by agwmon** [comment]
@1jsingh 
Hi! Thanks for waiting!
We upload our initial training code with FLUX. Please check 😊
